-- Add two Oregon destinations to the approved ROVIQ Local catalog.

INSERT INTO places (name,category,category_key,description,why_stop,recommended_for,local_tip,lat,lng,address,country_code,country,region,city,locality,postal_code,market_slug,timezone,hours,status,submitted_by,updated_at,verified_at,is_hidden,is_drivers_pick,trust_level,verification_status)
SELECT 'Portland Japanese Garden','attraction','attraction','A 12.5-acre Japanese garden and cultural destination in Washington Park, with eight garden spaces, art, architecture and a Cultural Village.','One of Portland''s signature cultural experiences: a quiet, carefully composed hillside garden above the International Rose Test Garden.','Visitors to Portland, garden lovers, architecture and design enthusiasts, and anyone looking for a contemplative Washington Park stop.','Allow time to wander rather than rushing. The Garden is at 611 SW Kingston Ave in Washington Park, directly above the International Rose Test Garden.',45.5187,-122.7085,'611 SW Kingston Ave, Portland, OR 97205','US','United States','Oregon','Portland','Washington Park','97205','us-or-portland','America/Los_Angeles','Mon, Wed-Sun 10 AM-5:30 PM; Tue 12 PM-5:30 PM','approved','Oleksandr Dmytruk',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP,0,1,'roviq','trusted'
WHERE NOT EXISTS (SELECT 1 FROM places WHERE lower(name)='portland japanese garden');

UPDATE places SET status='approved',is_hidden=0,is_drivers_pick=1,trust_level='roviq',verification_status='trusted',updated_at=CURRENT_TIMESTAMP,verified_at=CURRENT_TIMESTAMP WHERE lower(name)='portland japanese garden';

INSERT INTO places (name,category,category_key,description,why_stop,recommended_for,local_tip,lat,lng,address,country_code,country,region,city,locality,postal_code,market_slug,timezone,hours,status,submitted_by,updated_at,verified_at,is_hidden,is_drivers_pick,trust_level,verification_status)
SELECT 'Cascade Locks Marine Park','park','park','A Columbia River waterfront park in Cascade Locks with river views, lawns, marina access and a pedestrian connection to Thunder Island.','An easy Columbia River Gorge stop with excellent views toward the Bridge of the Gods and access to Thunder Island.','Gorge road-trippers, families, photographers, picnickers and visitors exploring the Bridge of the Gods and Cascade Locks.','Walk across the footbridge to Thunder Island for broad Columbia River views and one of the best nearby perspectives on the Bridge of the Gods.',45.6698,-121.8904,'355 Wa Na Pa St, Cascade Locks, OR 97014','US','United States','Oregon','Cascade Locks','Columbia River Gorge','97014','us-or-cascade-locks','America/Los_Angeles','Open 24 hours','approved','Oleksandr Dmytruk',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP,0,1,'roviq','trusted'
WHERE NOT EXISTS (SELECT 1 FROM places WHERE lower(name)='cascade locks marine park');

UPDATE places SET status='approved',is_hidden=0,is_drivers_pick=1,trust_level='roviq',verification_status='trusted',updated_at=CURRENT_TIMESTAMP,verified_at=CURRENT_TIMESTAMP WHERE lower(name)='cascade locks marine park';
